name: 'Git Log PR Action'
description: 'Provides latest git log for a Pull-Request between base- and head ref'
author: 'olivererdmann'
runs:
  using: 'node16'
  main: 'dist/index.js'
outputs:
  reverseLog:
    description: '"true" reverses the order of the log entries (oldest top)'
    required: false
    default: "false"
outputs:
  log:
    description: 'the git log'
